### ISSUE TITLE
article is not a function

### ISSUE THREAD

**Issue by itsthatguy** [nlp-compromise/compromise#405]
directly from your docs:

```js
var nlp = require('compromise');
nlp('Tony Hawk').nouns().article();
```

returns the error:

```
TypeError: nlp(...).nouns(...).article is not a function
    at Object.<anonymous> (.../foo.js:59:38)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by spencermountain** [comment]
yikes!
thanks Kevin. musta dropped that one somewhere. will put it back in.
in the mean time, you can do this:
https://runkit.com/spencermountain/59a44e25e563910012203aee

**Comment by spencermountain** [comment]
hey, this is now in 11.2.1:
```js
console.log(nlp('Tony Hawk ate the hamburger').nouns().articles());
/*[ { text: 'Tony Hawk', normal: 'tony hawk', article: '' },
  { text: ' hamburger', normal: 'hamburger', article: 'a' } ]*/
``` 
good eye!
thanks.
